name: 只下载deb到仓库
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 👇 自动从 Release 下载 deb 到仓库根目录
      - name: 下载AutoTouch到仓库根目录
        run: wget -O AutoTouch7.0.33k.deb "https://github.com/hell-ao/Rootless-deb-tool/releases/download/vv1.0/14697.deb"

      # 👇 直接把下载好的文件提交回仓库
      - name: 保存文件到仓库
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add AutoTouch7.0.33k.deb
          git commit -m "Add deb from release"
          git push
